language: node_js
node_js:
- 11.12.0
cache: yarn
install:
- yarn install
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: Mu6evKKaOUWOyOWcRLQR+BcBipIYQgOq+TrlkVA0f/SVBFlm9xok0Pugk4Z3yWndsLt0TGtutuQIKKCM/w9EZ/cvshe30mxfhrEJL6sNPirY+VVAJnlYJhnJniRSqMskYulmusbjbYzpvrVFL8piKTei3cHAlKcoBRg7jfdvP2YfSMRnfMaJNjht6TElhOyW75GR6+8Md3bBVhTXiLN0TbKtHEmQfiAyx71V4U9QaNWw3pSVJwy/f7eeDtXc6iJquXhFCgNrGbD+opwed26I6FXeVS5TgJUISE74pPBtI5962zwy0VkgPJ71ZUfLkamBkiz4i0XHEcsJ2NCCMqvv42PS101SDt+ztakEGPY/DyyKNQf/ngI7lCwyYMsQcbIdHGw7q0l4LKOJv4dyvWvcYGb3GC+IKU2d5Raf4sBoUvadeU7SCFqC4hkDYRQTUCl3EsZO9lhkK6yBwxw3WloQth84Grh2JnHjSuu6HV3aMDQjhXA928oeJBPGKJ/nugqdSct2mLb6k0WQrphbou8sy0oMqcptavgPLPb5P9DW9liXyU95m/KZtCvEy1+1lIT4Zno2Bt1AObES62vIfzu05DTOky4yTMQIgNdAXe/qribnWcnOtA27ztpJvbo80T9dDD9RFp5Xa1HzCovQudvXfcEjDrdQuXw4ggMRy8vEGkc=
  local_dir: build
  on:
    branch: master