language: node_js
node_js:
- 11.12.0
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: EFRI1EPHSAMFjL8Q1ZfwgAkGKI6bNVx4ckedWPWr4IV1tNVbFKxcBm2j+8tfZF1/dgaAkMU/ksPOwmHJOL3TqbF/yL3RaWXeN50kr2XpPFITP5DKNpv5wg6cbypKjMKu/t85U9czNbNQpNpteVS1m8YvnlDjhUDX/zb9nFyIER66Kagxw0NXKfaYyhqX0S+EBfqh/k7yioN/oxasYhreieqJsc7PdPTJ9i/HB24g1uQeWphOr9df2pRB/dZDxT0PUG42oVe5HrTlig6yjXnrEJbjWzt2IQAkyfKum2XxLEDzxHP+ICPuWE0TB9S50LK6YrlFZ6GqrcH3MYc7jgsqh2xvj7+zfSYHWq7WOyQpc5hY+D6lBY9lQ7K/lM/jMD9shBqn68xdeHP8yJloOgf2AVmcDBrq20TyknNdjxWc5WjsS+w5alVGDc9BxaXHSSiBhEdad2d/67ZW82RhV4Mo1ltW/u+N9GXjL8jJz27TUMBjSYMWTbnhVXZ2wHuXfnI2ImA+1oaWOeSpwoCLaOKKDQDBp0DyV3G1XhV64Abz4jWASeiBMs15Xn6YCl8wm4cimwIs9t3mep2FNI44i0DtJTg1P09e5Wa0qBVp1eZcSpCRTb3CIqkrY7WqFNKD1RkAJ4pNAwl2Q51Vxm6Ph6tYYjx+Rpq0naiq4gknENJ/W90=
