language: node_js
node_js:
- 11.12.0
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn test
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: mXjo3mbnfGypSJcdX+FG1Y1fR7a9asOWLvUVKmU0R21Y97YkLgcdr35RunS3rX1mWIx0JFslHmZfjH04TZKla0K/JCn3YVi69AKXIbVjQIgWKU7V0pnAyLoTczHqGpW9s2DOFmXTPSyH8G3/A9n5WYFMDfnJOAKTs7tk84EvQ+dThLWxCWsyq4/1SsDQgLCQT/Fi2yFifn8eAEnAUvHOV4DgsyTf0q/Yw4dPGV6crjI73XSnKq/JcCtLBaTAkO8lus8itKBtxkoSOh46HvTxUxQsFaC+6ES1cCH3wNvUW460QsTAcEf7sAqYnhEd6MVnirwV+0HTru4tjtCbvhB6X2wU5igde7vw66rSoctXamuALLbWJF3xQlzkG+7nh9UclDQ1zGPam1L+afXn2pin1xYaEQMcmFr6MjXePGPgoZNn7chep/v0ESiBXR0jB5KYUUzE7k/WDEg+rpthC7e5emn+Tqa7lKzRNWoHBCbexs/O14XSmmvdQio2ByJu384x1aCVhbwBZM12I5DvMUBNKo8JsG5HCPfhC+dTlKqinZxc1qLJV/oePwmY7wGReLWWkz6I7ONuhI9yzTl2Mr19wVuEJ60JDzE6m49CZvtxGQHihcMHgsVNTVqijSVkUHMs2wVVL7tABotLdNb31ksgS52jobJ1H2pAvNsGtc8u0ZQ=
  local_dir: build
  on:
    branch: master
