export const ADD_BUDGET_ITEM = 'ADD_BUDGET_ITEM'
export const REMOVE_BUDGET_ITEM = 'REMOVE_BUDGET_ITEM'
export const EDIT_BUDGET_ITEM = 'EDIT_REMOVE_ITEM'

export const FILTER_BY_TEXT = 'FILTER_BY_TEXT'
export const SORT_BY_DATE = 'SORT_BY_DATE'
export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT'
export const SET_STARTING_DATE = 'SET_STARTING_DATE'
export const SET_ENDING_DATE = 'SET_ENDING_DATE'
